# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ans
  user: krishna
  password: k21champ


test:
  adapter: postgresql
  encoding: unicode
  database: ans
  

production:
  adapter: postgresql
  encoding: unicode
  database: ans 
  pool: 5
  
